spring:
  thymeleaf:
    cache: false

  datasource:
    #    username: root
    #    url: jdbc:mysql://localhost:3306/houses?useUnicode=true&characterEncoding=UTF-8
    #    password: root1210
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,slf4j,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

      web-stat-filter:
        url-pattern: "/*"
        exclusions: "/druid/*"
      #        enabled: true

      stat-view-servlet:
        url-pattern: "/druid/*"
        reset-enable: true
        login-password: druid1210
        login-username: admin
        enabled: true
      url: jdbc:mysql://localhost:3306/techlog?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root1210
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    pool:

    jedis:
      pool:
        max-active: 5     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        min-idle: 0       # 连接池中的最小空闲连接，默认值也是0

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/**.xml

#debug: true
